description: Identifies protein interactions from protein sequence pairs
long_description: This method utilizes monomeric protein structure predictions to identify protein–protein interactions and model their structures.
homepage_url: https://github.com/guerler/spring
name: springsuite
owner: guerler
