description: Creates ffindex/ffdata database files from individual files
long_description: DBKit is capable of downloading individual files from external resources and creating a ffindex/ffdata database file pair.
homepage_url: https://github.com/guerler/spring
name: dbkit
owner: guerler
